Update devskim.yml

diff --git a/.github/workflows/devskim.yml b/.github/workflows/devskim.yml
--- a/.github/workflows/devskim.yml
+++ b/.github/workflows/devskim.yml
@@ -1,29 +1,39 @@
-name: Python application
+name: Lint
 
-on: [push]
+on:
+  push:
+    branches:
+      - main
+  pull_request:
+    branches:
+      - main
 
 jobs:
-  build:
-    name: Build
+  lint:
+    name: Run linters
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
+      - name: Check out Git repository
         uses: actions/checkout@v2
-
-      - name: Set up Python 3.8
-        uses: actions/setup-python@v2
+      - name: Set up Python
+        uses: actions/setup-python@v1
         with:
-          python-version: '3.8'
-
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install flake8 pytest
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-
+          python-version: 3.8
+      - name: Install Python dependencies
+        run: pip install flake8 pylint
       - name: Lint with flake8
         run: |
-          # stop the build if there are Python syntax errors or undefined names
-          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+
+  merge:
+    runs-on: ubuntu-latest
+    needs:
+      - lint
+    steps:
+      - uses: actions/checkout@v2
+      - run: |
+          if [[ $(cat .github/workflows/main.yml | grep -c '"failed": true') -gt 0 ]]; then
+            echo "There were failing tests. Aborting merge."
+            exit 1
+          fi
